### PR TITLE
Env override middleware

### LINKED ISSUE #20: Same file config overrides
I am in the process of moving our team's Clojure config management from environ over to carica. We're almost there, but one feature in particular is lacking and it would be great if it could be supported:

In most of our projects it is quite common that we override env vars when running our integration/acceptance tests. The way we do this with environ is by exporting the variables in a shell script before running the tests.

Rather than have a separate configuration file for each 'mode', it would be great if carica supported merging config maps from within the same file, much like [nomad's environments](https://github.com/jarohen/nomad).

```
{:foo 1
 :carica/environments {"integration" {:foo 2}}}
```

Where `:foo` is `2` when `CARICA_ENV` env var is `integration`.

I would expect that this merging would happen after each file config merge has been performed, so environment overrides take precedence. Of course, this does leave the situation open whereby there are, for example, multiple `integration` overrides in different files, which should follow the existing merge order.

Happy to implement this and/or something similar which allows for the same overriding behaviour :)

### PR DESCRIPTION
**Pull request by leathekd**
This should resolve #20 

If you have a second, @lsnape, please take a look and let me know if it meets your needs.

### CODE REVIEW

**Comment by lsnape** [comment]
It certainly does. I like that you've added the ability to specify the variable name, and the optional parent key. Code looks good too :)

Thanks again for doing this, and so quickly as well.

**Comment by leathekd** [comment]
Oops! Sorry for the delay- I was out for a week.

**Comment by leathekd** [comment]
@lsnape: Carica 1.2.0 has been deployed.  Thanks for the issue report and let us know how it works out. :)

**Comment by lsnape** [comment]
Thanks @leathekd. Can't wait to start working with this!

**Pull request merged**
